spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
            - "http://192.168.2.184:3000"
            - "http://127.0.0.1:5500"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
    routes:
      - id: chat-service
        uri: lb://chat-ws
        predicates:
          - Path=/stomp/**
        filters:
          - SetResponseHeader=Access-Control-Allow-Origin=http://127.0.0.1:5500
