package com.motoannouncements.enums;

public enum BrandType {
    HONDA, YAMAHA, BMW, MOTORRAD,
    KTM, DUCATI, SUZUKI, KAWASAKI,
    TRIUMPH, APRILIA, HARLEYDAVIDSON, VOLKSWAGEN,
    RENAULT, PEUGEOT, FORD, MERCEDESBENZ,
    AUDI, OPEL, FIAT, SKODA
}
